# Generated by Django 5.1.6 on 2025-05-03 11:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0004_medication_adherencelevel_medicationlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="dosage",
        ),
        migrations.RemoveField(
            model_name="medication",
            name="time",
        ),
        migrations.AddField(
            model_name="medication",
            name="times_per_day",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="medicationlog",
            name="time_to_take",
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicationlog",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="medicationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("taken", "Taken"),
                    ("missed", "Missed"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MedicationTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="times",
                        to="predictor.medication",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AdherenceLevel",
        ),
    ]
