# Generated by Django 5.1.6 on 2025-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0005_remove_medication_dosage_remove_medication_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicationlog",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
